"""Artifact upload helpers used by the job-reporter.

Provides small, well-documented helpers so `app.job_reporter` can remain
focused on orchestration while these functions encapsulate upload/parsing
behaviour.

Functions:
- upload_timeline(uploader, username, jobid, timeline_json)
- upload_artifact_from_response(uploader, username, jobid, atype, resp)
- upload_links_html(uploader, username, jobid, artifact_locations)

The helpers preserve the existing behaviour: try to parse JSON responses
and upload a Python object via `upload_json`, falling back to text when
parsing fails.
"""

from typing import Any

from middleware.minio import S3Uploader


def upload_timeline(uploader: S3Uploader, username: str, jobid: str, timeline_json: Any) -> str:
    """Upload the job timeline JSON and return the object URL."""
    return uploader.upload_json(timeline_json, f"{username}/{jobid}/timeline.json")


def upload_artifact_from_response(
    uploader: S3Uploader, username: str, jobid: str, atype: str, resp
) -> str:
    """Upload an artifact retrieved from an upstream vendor response.

    - If `resp` contains JSON, upload that object (avoids double-escaping).
    - Otherwise upload the textual representation.
    """
    try:
        json_obj = resp.json()
    except Exception:
        json_obj = None

    payload = (
        json_obj if json_obj is not None else (resp.text if hasattr(resp, "text") else resp.content)
    )
    return uploader.upload_json(payload, f"{username}/{jobid}/{atype}.json")


def upload_links_html(
    uploader: S3Uploader,
    username: str,
    jobid: str,
    artifact_locations: dict[str, str],
    title: str = "Job artifacts",
) -> str:
    """Create and upload an HTML index page linking to stored artifacts.

    The `title` argument allows callers to specify a custom heading (e.g.
    "Sweep job artifacts").  The page is generated by the underlying
    ``S3Uploader.upload_links_as_html`` helper which accepts the same title
    parameter via the object name context (see that function for defaults).
    """
    # pass title through by encoding it into the object name?  simpler: call
    # uploader directly with custom html generation instead of convenience
    # wrapper, but to minimize change we will extend wrapper to accept title.
    return uploader.upload_links_as_html(
        artifact_locations, f"{username}/{jobid}/index.html", title=title
    )
